FNiagaraRenderer <|-- FNiagaraRendererDecals
FNiagaraRenderer <|-- FNiagaraRendererLights
FNiagaraRenderer <|-- FNiagaraRendererMeshes
FNiagaraRenderer <|-- FNiagaraRendererRibbons
FNiagaraRenderer <|-- FNiagaraRendererSprites
FNiagaraRenderer <|-- FNiagaraRendererVolumes